global:
  resolve_timeout: 5m

route:
  receiver: telegram
  group_by: ["alertname", "service", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: ${ALERT_TELEGRAM_BOT_TOKEN}
        chat_id: ${ALERT_TELEGRAM_CHAT_ID}
        api_url: https://api.telegram.org
        parse_mode: HTML
        send_resolved: true
        message: |
          {{ range .Alerts }}
          <b>{{ .Labels.severity | toUpper }}</b> - {{ .Annotations.summary }}
          {{ .Annotations.description }}
          service={{ .Labels.service }} alert={{ .Labels.alertname }}
          {{ end }}
